nameOverride: ""
fullnameOverride: ""

namespace: rsshub
destination:
  server: https://kubernetes.default.svc

labels:
  app: rsshub

source:
  image: diygod/rsshub
  # renovate: datasource=docker depName=diygod/rsshub
  tag: "latest"
  port: 1200

env:
  TZ: Asia/Tokyo
  NODE_ENV: production
  CACHE_TYPE: redis
  CACHE_EXPIRE: "300"
  CACHE_CONTENT_EXPIRE: "3600"
  REDIS_URL: redis://localhost:6379/

redis:
  image: redis
  # renovate: datasource=docker depName=redis
  tag: "7-alpine"
  port: 6379