---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wave_exploder
  namespace: argocd
spec:
  encryptedData:
    channel: AgBrbmnpwnYrhAEgsjANqotMZ4+8IdQHK9FXUh7BbnYfWM4ZoqCY6mlhyuyafBjo5B+Q9LeyZwJ0slHtDmJwO/MujwjtSgZUP+9D0wIyoJPSoZzl5yWdJ6vfPU2Ytr6EbQ9EyYaOltmG8iDLw8NhdtKTtwyWYt1zhgSMSwK0QGLOvzscQksgB2Uzm29ISBfDmG3Fv3IMms9tatWU8jDtNcEdyq3oMhWeF3P4tEHozObvr9NaKk1htxxFZpvjhrqhWO5Sa04gqxfk/+5Y8cbtw6Ou3p6xMmKe0SehLSKlDgZaCJaxkIkNaQ5lhP1Srf6Sg9H9UiqepaolS4+IaS1r9VYZfBv+g8vryUOsPQuyGqBBUFIc2OcaF8wCUn/CbCwv0fXasMyXX49BXo+QeykEu0aWNjNj1Y7UlArbBqRS5EaIT5vQIdNNx6D0lbMFFmlHYp4KQ3bF9FnAEtneeDmWHz+Zos4g3YGf998OlHfTxb4wJk9ZAcwi/wucxHT2WFi4VPPyseF8VbOJkikyXo9wOpLv1sb6HrnhIklSzvZVtoptAYNwOI+yZZAxNDY4B6chHxk+cEJnH/6ChFt8OfjUWYexKbcNRmWpkUVwa6aQNom8zhGQJLdxSe3mqqyRt5/bkDNzhwUWRmeTj3pqlAAviz+PuVT5oGcV3nwsT4i8VecCRPFnBp/iNUCkJuvAHr+bmb+j8PcaNTGru0DVpo9B3awjYY4=
    token: AgAypJnyM42taPMnlXz+rVzQnJzkLmRYaBBpPZ9OnmWFFtGHDJo1lDFI8S76jk1Pwq+Jhpu8e+QT3LF/Pe5pyoIiwVsAlDDi9YTnxN91sgvdIMGGWoZ0WJPQ4CDtyAR31HqR1BrCuNA9z47xfHDvZp8HwrecAyiHYIXJFxrQqHOdqhTDSITIaU+PRqbykpMLZwwAQd7e8HQ3TG8CKre37bty3up6OLLf2/C2sAxuRwY3VcPRU2sEIctenCAWD6mizsHXGXMPWr+LkRlYRDMqjzXD2k149eV6DROOCYunUlN1+21Q68wkZtrE8aqwoJw8ZKaUfSEQ/bl9ERlF0VAMrtKVKrsnizSFpmHThBkgBrlcqsWWIXhfzclmwUFXXLF3n/Xkfyxa2UypFknmiJz9LTMU62Cdsitmub6Wq0c2QaBlEnBug9ydQDokhPyTjZMrgkEtOOT6LwO+2yea+XiVqMxPfWFtuOzdPGSRdM7l1ILYwaLbrUAewOmdZ4vAIqPzmnWjIJszHneCA5o/DYRIhgr0HSVb1BhahqT17qp2afyLs/ltrSlaIwOiitiBzayfGvjxWZ4ix8F8mgpwfh7N2aFsCN5pPllNH0bGxx/qR0lCBhakqe01cpXOFnByjNpUz+tmt/K6xgeLoMaCYddIg4F3a6Ggod0/h34CEUaeAZmA7Fty0KWTjgRm6LzfrKvnikWcvwivEItN5Olt+tCbDql0n4EXXekfsg+KksmpM2qzj9UFItqvniyvvSmFdRhfOgfW1ND6JgUAwAL4GN0VtAjE2ub9yGeZ+iU=
  template:
    metadata:
      creationTimestamp: null
      name: wave_exploder
      namespace: argocd
