apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rsshub.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rsshub.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "rsshub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rsshub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.source.image }}:{{ .Values.source.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.source.port }}
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: CACHE_TYPE
              value: {{ .Values.env.CACHE_TYPE | quote }}
            - name: CACHE_EXPIRE
              value: {{ .Values.env.CACHE_EXPIRE | quote }}
            - name: CACHE_CONTENT_EXPIRE
              value: {{ .Values.env.CACHE_CONTENT_EXPIRE | quote }}
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
        - name: redis
          image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
              protocol: TCP