miniflux:
  ingress:
    main:
      enabled: false

  # For using built-in postgresql
  postgresql:
    enabled: true
    persistence:
      enabled: true
    auth:
      username: postgres
      password: postgres
