nameOverride: ""
fullnameOverride: ""

namespace: miniflux
destination:
  server: https://kubernetes.default.svc

labels:
  app: miniflux

source:
  image: miniflux/miniflux
  tag: 2.3.2-distroless

env:
  TZ: Asia/Tokyo

db:
  user: miniflux
  database: miniflux
  password: miniflux
  port: 5432

  labels:
    app: miniflux-db

admin:
  user: admin
  password: password123

pvc_db:
  storageClass:
    name: fast
  accessModes:
    - ReadWriteOnce
  storage: 2Gi