apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflux.name" . }}
  namespace: {{ .Values.namespace | default "miniflux" }}
  labels:
    {{- with .Values.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: {{ .Values.source.image }}:{{ .Values.source.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8084
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.env.TZ | default "Asia/Tokyo" }}
            - name: MINIFLUX_DATABASE_URL
              value: postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@miniflux-db:5432/{{ .Values.db.database }}?sslmode=disable
            - name: MINIFLUX_ADMIN_USER
              value: {{ .Values.db.user | quote }}
          volumeMounts:
            - mountPath: /data/db
              name: db-storage
        - name: postgres
          image: postgres:17.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "miniflux.db.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: miniflux-db
  namespace: {{ .Values.namespace | default "miniflux" }}
spec:
  clusterIP: None
  selector:
    app: miniflux
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
