apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflux.name" . }}
  namespace: {{ .Values.namespace | default "miniflux" }}
  labels:
    {{- with .Values.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        {{- with .Values.labels }}
        {{ toYaml . }}
        {{- end }}
    spec:
      containers:
        - name: miniflux
          image: {{ .Values.source.image }}:{{ .Values.source.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.env.TZ | default "Asia/Tokyo" }}
            - name: DATABASE_URL
              value: postgres://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ include "miniflux.db.name" . }}:5432/{{ .Values.db.database }}?sslmode=disable
            - name: RUN_MIGRATIONS
              value: "1"
            - name: CREATE_ADMIN
              value: "1"
            - name: ADMIN_USERNAME
              value: {{ .Values.admin.user | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.admin.user | quote }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "miniflux.db.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.db.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- with .Values.db.labels }}
      {{ toYaml . }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.db.labels }}
        {{ toYaml . }}
        {{- end }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:17.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "miniflux.db.name" . }}
      volumes:
        - name: {{ include "miniflux.db.name" . }}
          persistentVolumeClaim:
            claimName: {{ include "miniflux.db.name" . }}