apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudflare/helm-charts.git
    targetRevision: main
    path: charts/cloudflare-tunnel
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    helm:
      valuesObject:
        cloudflare:
          secretName: cloudflare