apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    - cloudflared
spec:
  selector:
    matchLabels:
      - cloudflared
  template:
    metadata:
      labels:
        - cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: tunnelToken