apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared
          imagePullPolicy: IfNotPresent
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --metrics
            - 0.0.0.0:2000
            - run
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: tunnelToken
          volumeMounts:
            - mountPath: /etc/cloudflared/cert.pem
              name: etc-cloudflared-cert
              subPath: cloudflare-cert
      volumes:
        - name: etc-cloudflared-cert
          secret:
            secretName: cloudflare