---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: argocd
spec:
  encryptedData:
    tunnelToken: AgAWmntjzX/2Ev9/wjcdjyQbv4hoWH6tGB8Xc4kDpn7F7bj8UdDyba6IUK3yilfQYCtS5jp3GQCgG8n+HyRD63ka7I9vcVm21lopetFKS1zxboLmeEPNcjJPs983qbpaCMYYmRkGU7mk9Dly6oRvsM+TX0udXFrDe7rHS5KU6RqxPchuoMdJiwr5VdaXXkVehWilV4ape7UXeQ48ESD4+4u3S1hKVkv6uD9KaWW5zQ/wNBHlNRW+eC89wgA58AJUtPQrnjYiuY0x9pElyedOulisx2bPHDfqhWjWdxClmIj1nluXF1je/5nQB5umRJ9LLyURnEJTxwcM1p36qO710r919ZSX6hlwFzp+04Ac8FbFB82axbbaKJo++afIT8ZQNTka35uuoaK01eGqzXtYDZ0H/IWSMR8H/RGQVgjv7OB1nQm2n7pF7QGLSUz5ulgbHju4fBziwMJQYtbEP9QVfaR04VSvDZJc/PJTnXkSLorxO6YwR4wwlkyimR5N0jdmGLLVLHaEMyJECRchMQ/wssogdQrQqv8FPzapcMaFNQSHEyLW0aoT1VzEVpk6czxd10dNGw1a9jh2z3sPeDMp4/0iCiTXu/b61ajgLP2sjX1HiCcnr0yqV9IX/ZFKVuDKKdaOyUWvYU5Ovo9flf48FMgMDJZXR4Y8pxIZcnyNp6nXa9k/YgOIknMMgNP7qQYon/Kl8d+Bv3JXPSsAvuwgqp/8AZEzu2S66F2odwAWmWNSymc5+AAvpZX9WPb9Uafpd+d7PzgPXieP6gVEUmLc71jWJ9SP6oeRQKciDO6d5VgvdHjZ6+7vBkSWRR2xLmjdLTJoccfWJUyz5j7am9lwgG3fHJLWDeXjis67DS7RylUj3vblywOlfsjEA6c=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: argocd
