---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: argocd
spec:
  encryptedData:
    credentials.json: AgB1PlISDeIQlTnBrnoUYiWroCK9zZ81lvRa2oSVXaRwwbT7Uup7AbXcCnJnkp7uSe+hfDM4YVvIKZhOfIN0HnlARXtYb3k+vv2Nj8toK47m4xCxqrt/ffOUihSDwoQHbeLr/S1CgqPCS9pteSA/XxxblhrmfApMlOmsjCH514POlUMOqyhrJcrUU6PJi4QHiO2z0KNkSJpOF2JOHN43Xo+lsZa7b960HJw4ZQRpAgpJ2vjhjzyQXPhQAYYSKP9OdtJV/hx11VvEgtXOOn3biioxdO4pI/ebmYsiFOlIPzJsV7+LNpfliK/VWKgC65FFApravEW2n8EEYNWuH26S6SNUcIXwXJsnvhZ1CAFBItcTyako+uHiXj7OU0uYvBXWA8rakvWYy9EheL56xBLxOeEoiMwQU3qLptkpBgWO5Z3MskdpGiIHU+8GQoPoItStvkyKNLK2GJoB/1eREkmikT79OqQidEH2qDEKzx8HI9tfnSr+pNsaB+3UMIxWF1ckQ754k34B80FHp4+iU3JYZ3P1xo6WMEiZyn3VsJ6eei7oOuxfihOV24S/MxMzUJnQZEhTimHk1+UAIqkP0WuH6rcvUigS1M1X+yDRvz7iunzUd11ruvSLh6x1HTR3mz1QjSaCwM8k6J6W1cPmSwpGKBaWnCBI1n+e5xPSC2bleNK3yFmXsiSOJOSNp2ubCPUip281o3voH8y0TdiEKZ6ZjL0rHRDBZtYLhJn+ChbYpDlbItCi4x9TAUDRiUR8PgM5TDFEowTBY+ARMg1WxHP3UqMwRqAiy1r9qUu98FsaUPTUf8lMbGyn7tAU8w8kO1s48HqigygYp9KyIxo6TcMhcww8Y+JJbDsWYBQ/AGF8m0FoRQzvj5srKJedwggeklQ+g8ouiEFZ2+BtGJBSzRCNU6n3jKtjrTr2Uj4TwPUROiQ4wA0T06TVBtmu5RFpfduP2JADsTqy2AEdXw7Jdja5r2OxjQHcb8Lh4gjHT2t2Rd+kjRWLqma4oYWuV3WkuFxyPQnf22EcEjTFDwWUmdhSCWJ27tihqX0XPltq0+O+NcMdyrntUu2dRXg3ESQStopfyuCpDqQKV+nIPRGVHzdernE8gBDKFMfHuV6GYK4ZYp2FiAEtX8840qrM4Hq4VhkZtfFdHNL5vcw+F1cYUyLqH1ATun+ymqO+/PRae/LJ/bq5njN1z3ubav8gs+8=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: argocd
