---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: argocd
spec:
  encryptedData:
    credentials.json: AgBtIMwucbxJyP44+ksQkg+6BTbhTnp4g2H2igdBfO+PZQqd4Sgq27V6b1Pac25Hn3tsKKO2i4qbXioGOmUnf8GjOQZYR4KhQVb3LrMC7ChAqWnbHJJIaXJEmLAOtvK1GQ6iCl8rRhSIZ+rhR75ysaGJvvoVJsPZKa8jkrCBBjwiDc7pIwZKk9WRwM6R3TJDjNSxgXJ0vTM1rtCGaN/BQyikR5pKk4YZkp8Irnq+0S07EzXbQX/rRpsYMliQ95QtTCnvQoF8o94O7Gb/Mbw29FiUXwrChnb21rDmksWi5RFCOcxg75Mvkz9V9L2DZCZ7hJgj2OXnE6j2G5USwEm4zkHF/3zEw9I2g9WKgG3CGgcdnZyYVQRKPREIV3u0+WV2hTKZvnseTxd+LYPEQf4nYua74gtRp9MQP51kTB3d1y6XdBhEhjQUTss8+XomBk4pBFI6xRboj6XM513o1HCkGJocKXATnS0B+97ayelUpglHbHqdatRYFnqdnuNhB+jWCujDRKxhMGBjd09z2U1q6P5DID7GpuTCDcj3KF5b2kzvaRXbtUk9ByNaIWf29t68kZ2RS3QSBRNZYuIUMj8VDP2TumWS9Az7bCAM3WQ0MGWJ8bc1E+neNuxJP9KVYYdtbRFlfrBTp3JEbFvhchCfSgD/lGUlscNZY61PaiF8+RU9uDCjjdwaoFLVXIcFGjwH6GUkjf2hNZq1pPsrfFGjI34tzyT+dqYQnpW+yxMYk9Iijx07tA4KC/M+SDHencL2ILLC7N5xBTNU2ARDSEiFJ7ZV5ey1iX4Zetutj9uFrW+62OvTR+iXfJ5EfUQ+Yby0PqwNGWZj2Ekuq7hY4TBwAEtD9u5PWBLJm2Dimf9ZM4vZ+XI6NzG5aUsjcfrtbT0ryShsVH/nTbN5jypqu0Jef37P665BWChWcGYrHrxdHtTAhsLsdR7wmJL3y0fSnDbk8a/A3ejppp2yLryB+JYaBBsFfJDWRNOt/Rbw99tszGA48s9um+1REV6+SLH4mj+excIwRVXHQvaYlZw0C4pIfdktj4KVgXchWgQnF/x9Ir+l9A8Rs2oWLZMOpxoA1z6xVks5jC4YWFo4y1hxShD1/PL8IZR/Jmxkc/3whisr2B7dYtmlXWKkdUXCTsgP+LMqH09DuAK3MgTfGLqJx11r2OHuLXhaNLItGkT/aQ9nhnt+satnVxbl+UjgW2Q=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: argocd
