---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: argocd
spec:
  encryptedData:
    credentials.json: AgC9vNIkMZflNHTXAtCGJXv3v6DsHfgzDMZhcpLxwc7km1zPIfNhEcM1EtiJ/sUbIZQWYvBcrD/jpSsA9XLjx35SttxnBBY4zcUEkhkw1XOkJVBQ7cVwr89aOelRDvhJ0GEOrYsahsxhv19mDklxW1JKRhXmag2ZyeUahel3oZsJS5lqyOLqKnce0YVKBRafPp3nDHF60Gy30c5rToMwxi0skpk0lmA2dQ4O1Ca52lLGamWF8A3yTs2x+YCpRjk0Ml984RUNodao8NofPBR2U36mf5iDP8PwFSTCJjrYEMrwDgCF9fp55cKJGGhLT4rMWOW2TEvbw9zDE5D3G6aKABgCPF5/ilj1jDIKKEzXEJ8qlygr7/ISY4xk2/BfhNuuwJ1w74y5wntmbV7O2q5qfllVNP/qvBqLZJu4GP8iv+x4w9uzsHRJeDh3BhthkjeloDhirNSG70Eel5USadA2ZFt+OrVcumrC78IP02T0Id/QMP74g4GFO6Te6kUXM98+WWPq/Fjwp9zNkSmS30CdbFHIIyAb+s2T8KBbyufF4elV55Wz1iyUujq5+yCnAgWloeL+meiYbfZj6ReC48F208lLdqPDcFFUdSSkAosuNKakC3E4Hdiy6X/j+4zSXpzdTX3TV08+g+RibXx3xQ2TdaN9jGfGw9gxF6fgzWUhrOzYWngzsUd0enYQmg3n6TtzWVImIFJ7KOzQkwv/+RcK2wau7zckI4nLvDHJdR7L+cfitE+iTTZ4NJ5EZZe5OkB/J/G2KffWJtR5dIVzgb7fgv0LN24TXxu6F+uB66tkUUOPOww4rSOODFbWJ5t8Iaw7J1nXOGUS61ojz16mNOIVnb/p0tYwngpnteBVSrwj2b2lrbsDZk+FauUsGFSgZQCpVwMN2P5JLYbNp1ddVw0FQfLQF+lf30f92wC8Py5zZ+DeIVG5gnCbCW9JhJuf8bwl9ck4YVBj0vEJums/TFEh8aBdk5lgB4fQy89RgyiVphNOPz/cKm7FbmKxMxjIe7+G0HS3B+Q31Mj7/uElkxsdgE3VxX9AwrTCFT0/N3mEx84m3SPTQRdNmAGBYiF3oP5UdbMK19niQCGfIerLZg98LSCLlXQUh6J7cNTRgg==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: argocd
