---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: argocd
spec:
  encryptedData:
    credentials.json: AgA7q3njXKzZ90oqls5LrElbxyMyUzawq6RrrzCaU0MR2vnw5su/LrNt1SoM7oOvt5jKrJyO6GLcSZpyEWqSFAWOqkLHGtuTds7LC7HnO61Lt5cHBxCMi3H0XOdu0u7xb7qU38U3o1LMXx5QrJH7iZCtZyX2tonHLUY1hMPzrDlZ/aXUnmDmVoupvZZZ5rEKg0RaKQ33wGmjz6ei3s5aWgUY+PhlAquVlnr6YLQYHtPiwceE/o4cUntve1ZaqJfebEBajnhJ/I/0xNKGTuCF8qwqKZL88w/XEuEQllTxARXa6SYx80IoiJfP1KOLwIV05v+VUo12CftqzcagcBeQ1Ll2vXNKCyOjQ9S6RiLxnFQxoCncge1B3DBFXZ7NRtJcj5m5Se9M0gdPjoWNT8fRxsMlMEYietMv18juXyg00pnG3UW9YAQkL1JMDK8515SgBINxzvOe3SNq6l6Q9Vkl4a18bu4XhAx6M0gtCCWQGXWDIJmu9ZEbc4RfTcxzYJ6WmlSIDsn1SmvaFaEMBm0NBznUF5iVHp13ihQZdlH7jMoqt85XgQJBeeVXHwvkyEtE4/pJ3etmVRR6pJ3UNFCr2ayZl3XmEubXgHl/mZfLSJeM6IYvvcBd+PxvsuiMIe3oPhGuUO/Hg5c+xeSP2nJHCuk3SH9mcRY6m4QcQSFkAW3s7z0bPLZ//9DFS4Ek1UU+c439VB+Yf0YpecYIjCiwfxWIfwV2SOZPZj3VAQuUevZ+IpB7cgIMZKFNleNlIwz1ybb7QuQMk9cruxYBS5U3OUKFd3vXBRtby9GXCEyvCtRlxMfMekQRYeFJsLREY0Fr0vJWBtg3pfayOIYr7DVdSC4rZIW5v3/LLb+D3cs/Fq2bM6W6I8uriIplBA0KD8rZDpnyNXI1/4uYK+BumBPg7rxT8v1Nm1Ld7ADuoSk+cq2NxX1pQ6fyWRFlS3TsipCMA/2YYPpkGNwJAqJ3Bb8o4++pOvIypzG1yCfiQKQmAFvBw3X0mdZgA/wPfo3KT6jkmtXLZxx08Yj3kP+Z93CETXzrhQuTq1dhuSF4pNaqqnDpSAcawG3OJu4a30bT86TPU8NqzZMG2wp8pgQMw0UveM1PMSnQrn9V2+UjOdfu102jR+uJYvUp3M4s8Sq+aK3DS3PSsrK96HdSfdrNx87IDJM0E5d2KjmAxpMoepCbEUJ/bLJt6DUwLfannXA=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: argocd
