apiVersion: v1
kind: Service
metadata:
  name: cloudflare
  labels:
    - cloudflare
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    - cloudflare
