apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.db.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  storageClassName: {{ .Values.pvc.storageClass.name }}
  accessModes: {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}