apiVersion: v1
kind: Service
metadata:
  labels:
    {{- with .Values.labels }}
    {{ toYaml . }}
    {{- end }}
  name: {{ include "freshrss.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: freshrss
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- with .Values.db.labels }}
    {{ toYaml . }}
    {{- end }}
  name: {{ include "freshrss.db.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    {{- with .Values.db.labels }}
    {{ toYaml . }}
    {{- end }}
  type: ClusterIP
status:
  loadBalancer: {}