apiVersion: v1
kind: Service
metadata:
  labels: {{ .Values.labels }}
  name: {{ include "freshrss.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: freshrss
  type: ClusterIP
status:
  loadBalancer: {}
