---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wave-exploder
  namespace: argocd
spec:
  encryptedData:
    channel: AgABg+b1n5/DD6WGWpWQqvsRgOQAIp0i7ePBFhWof8mJSGyx2f4NwRN7iMOaBvOclAA3vRPAV/J3CTLdSlBGFG1Yb02BWVTEswe4tT66pPNC6JSi1jvaFR5Fk9zC08W3zVS08QUlTji71KNsdXeCJyEO6EPD2ukDQGfPwpfhknh8xsmmjoUP0lcVBwGJr8Y3P+gNuDvZOSzb/BArFpt0TdEWTOFR6z3x2CFPuhUu0xv21p7MqRh13BCkW+grsw3gBtM///T6mtJOllfdewW5t8xW7+wDLDr0DOrC7jfie8zjKRMtB5efD5uz2NSm+R4rN2EQOAsiyYVnD4mPbenRNeffFn9VZ1UffetvNaoG5JArtmwUaW1yBYQlKmqgAZQ1pD7JCCNL+ZUssfcfV+nKLdRUMS1LPtESQHnaKC5HbGaqg9NuqRHKT/H1ZoXXCmxtJeeZFbNVQ1Rv59qrUjmz4saK2AOgYCHvrIVWfigr0LFaxeW8F9W07CVWy+qQQFurAx8PYaMP0RRuR47i/4b5Oz3FNfwrv6vU/BU7sFVkcdJqZQbxhB4DwWGKwp5HPycAGDkHJHjqTMIg0YO0RJl+T+lqcCs9d14B95Rq559TFPe7lR33MNcP96nrEJa0pMP0HKXYgbt8AG5gvfe3iSizd2JMaASbkpUCoIDaQmoHjW0qgIftzvV99Fz6JqdWw4b/IPe05agqzjie7O4B4lQyuzDR5HY=
    token: AgBW5uf9o3Rwoo2kDrlOjgeHYS+vJlpdygG6bh/2hQU8YZWp23covRTpW+xyR2KIKTwffqYifEP9RPiHTYtf9+wFlcbfC0oDdgajLgkgT4cKRhnlwF67KOWSU+0p1fBeKFYuk+4kmMzOvloNFugzs4uRLSpKO5I7Ij5NRdg9nD/y3Kp8KhSGiE0URSWCdlYijKyGBl7BrNQaNUeqGpNZmGy316kaOFt728L6cPtqQfkVIpCYwg4mMkUzM98NwpPn/pM/CRFhjPzVuWf6mbOIj1TUW+FHLk5UzVnixLuRzZpb5vAzdPzHJeh6h30TXfUKk4EDfqCbPxfgnx8XybPLxetp3GpZyPzU0QkM8g+WIiyPapzN3ayDyDs5E1akrI1y2r1q6bE68CS+VunkY0Lj3nOf/J5rcOBrIgL3WVNSmIlvXYgHAFfDcU37RLWasDcKEPPA+790nS/zQEOyMhmqSEXQajQ+MdC29xvm6ZprkAAquFY8kS/zEkrJs8mUtAJ/ynxYyUZAwQtRfma9mAdoUjLIRGWjLFgzfg2xj4UdPfKpWeQ7YwZ3dGENHNOV6EskhbyrqN3ZQ4DSRD4R7AiRhK4FhZV51ZZ62+RanYen9bH56lO0rh3UOdZz3B7VblA4xpCX5aLBPX5syA/3A8k5OSlG3K+wlIoX+OFpxLHhWs9JKXwIQ/Cw8ycNMY44UNakUBL33h3xKoJlONWO21pBG7GFS538UfS2ZAkuc5QjamRDlj1MMMuLJuJK+HNXrQcfcpL2fTTF9Ub3sdEaosPN1jsQfTcCgCIu6pw=
  template:
    metadata:
      creationTimestamp: null
      name: wave-exploder
      namespace: argocd
