---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wave-exploder
  namespace: argocd
spec:
  encryptedData:
    channel: AgBWtRH3CGOkfxlw3MN+vpMh45uxWGBZyppRQpYOmYR2ABWrsHjAoD1dJLBdKzij4XodjXwCfxP/MrXZIF6vaWlkgiQkAuCwFjJse40UKrJUzcXn1f/ZdtR/kUJFY1v8RowSvg19EqQlHEdvlLE2btrP0HAXudlUbuuigehssPoHCNSoiYZp57SCQU57sGJR+YMM/6F4DXtvS5IPcauBIg++bbw/ult+HqBzXKEOV8BcI9ljIdmVw0xKY/YyR9QhlkpyJ4r9H6dMXcwgAoB6Ai+rv+dRWMrPnEh19MwU6oPGS84C4Aj6qu43cxt+mBeq2M72Q5AteYJXlZmay+uAgFzd3Jz/lc3/T1P7hqMbJvScomR0VGyraCedRB8bDkjgwPT7tWIyEmJoN5A0BnXx2o91wAc3i0sRza1Te/uwpPnV2v0H1ONbdHAL5SxYZOfJP/b9r1FFkPdPSm1cYjXcoLgMYq8gUt6HAlvwWiI1IP4U9WgQvc1lQn4S7Tm98NpAxu6Do5FjHkz5oa1H8JSiDXf16ba8JN3G4/29cMEuPG16RbtmfM5g13sQs5vrvixBMfnBDlwqohDMG7sm1XOcy6F0SJktAQpUlkMBmVQ1Q2m/4R//bglWRT53cHB92GET7es+4AmKtuDNbHYT3IplvCQkxLkaLt3q46rFxiIeW7dUHXr3oWettxxGApKyTK1S9mtKo3TqXFkpYqIekaV+7gxRDBE=
    token: AgAxqJ9ZDRj4ZPEBIhJYFWkep70vtFWCzeZcxaX0+dFHidJh5GUwzjhQvk9HCvEQDlHFXiR0Ju8LVnVd09jbY305jqhrE4RtoVu9iUlCyx+UR72f9sIs5e03wWHZGAxXuGuH9lnguMTloet/ojzAaoSh7FwDPFe5CpJri3fi+0ouhE9EbuFlRntK7Z5ODBhhZfA7AYpKfmngr2Od9hWN3KQ/0ZpxY5mc1vBp1zCp/EdYYtjnOkzRT9AmCkGJE9tfkSbAGZ2901/AD0phvv5TuvAZMEtS383Z2xWR9mQAoRaR4jCYynLPlixHzt+eZ6rG6GOvd4s35mrWO/llS6KOKSCUc6KxN4NVKDHvGwOZq9GiAMWW3eW4QVgMEOaYkFLw+l7PBegpPAwLVt4UJx0JnALgxZtbZvaJ+pB5ltZwjlzU71SlMO8aCLrV94XhyeFYWwkszZQJlYq1LO5ISfaOtEZuaqVGy5Q8kMYmNZbeJqdBLKSa0G2KYIJmIIIKr4FqXFSFab21rErjT57nLV6S3TcFL9XZxDSk6eocww8KtcRMwUtc6ma/5gRxBx+R4vqmEvF3SlBtxg+cScDJz3CuoKjI+u70jlCkoP1uIvqHSzmVsK/OFOApP+mtBdAJgZKEhFYxEpW73YewKIqRAvmIxp/Gajaz7iXhLc8aA89j/XhG2cFAyRM811Hgi9sidyGwUpoG7SL8MHvAo2fpJk7s4/A2dsqvp1bfr7CcV4WIuJSzIIZ0A0d+rshcwL0lzTF+qU844WjZEVrqCyRfDJZCa+jRmReQ6L5ucDc=
  template:
    metadata:
      creationTimestamp: null
      name: wave-exploder
      namespace: argocd
