apiVersion: v1
kind: Service
metadata:
  name: wave-exploder
  labels:
    app: wave-exploder
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wave-exploder.selectorLabels" . | nindent 4 }}
