---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: musicbot
  namespace: argocd
spec:
  encryptedData:
    owner: AgCFgSbsQ4bMD0o9GMYzQN05GB1eEIxCsFQPvLBxoay1lu61umw8by7sSJZZDNArv7oRXWaON6NzKI3KqD5VlrIVnwg8qM0VwSUN2XxXh5s/Ypcov+Lua6E13gTGfG+qq3K+QyfTvX4fKEXPPFP99QXQzh+k8VCYMRiDBAbepF0/XXuVCB0ka5Q+17ccLaHp6lj81EHjLo1kOOlNLn+URGB8qMvx/1gJzahdYjJRoEvMVwptECUM+WR32yl++kfMz0jH4mBePHAqFIgytMejqgVR1dssGuyVuc8ZVlIGOPyCZn5QFlYfhXNJHjOwKaEyvBzdT7783k492t0QRNHhSShPcdLtJzcmR9lkkrEM6CoPQycjbueeC8AJlXgHJfKs/O92mFeV3TLJCp6nmvakh5V3kAo2SGn2oK+DQROGIai4SdXfc4qTKZC2XwpaZakAUIgrVIGtBlK+LnVkLWn4s7/WHvWdWS57xrUKJgJJKpmjVcyX84wDbF5sLyDUZCv4cx2zEqbPWtcZ7vKi47Ew02nqfHQj6PTLJz2sB9nnTDZmXnOBzCWvvr1Bte5MUS9oCErjuUB+Jjj4gfF9VNWowkMMA16AHzT+Dq/DXbfIqj0zi39Tpi1Wsvf2ure3DISw60x1cf3pAAJigYVmKxw6O+xCgnS/npkIu9sdMNHgAwwkBLzTQrvMmV1tS4Yu9TwcBRJZr1eVWPU91ly974ytL3LPjZ0=
    token: AgBePkPPgyOfcV1R+cw9D4n89ndu7SjdKYTkfdEB2xqSi4roAxtpDvHuALqEolXbu0YGcDrINuYA4XPvo27aCP7ESHIEZxE6oeiRtYOoLv/lVkhQNgOf/XsIkikSWQ0h9cITeOig+nAcntQoLQy0/0LUlj/1UXIposUrBYKH4dAdwhusWcNm8cx1qvIU4aUrIGKQOcb0wVX1cOsulB4VtRJ1pTX/JnN4KKN1M3sHmgzBX8jWVIGzrwKUJnsyQ75quJ5c0NrX/yCqY0LqONEeF39ltrH1duPKund+rFBC0EvdsTdNnNkwWR7T25rczcWQf/wwxkdXfLVNVQaqkCje+ZdhQBRJ95Vp3UqVXL4jBOutw3oEBPf7uWe0l0UqwiI4rPp4I9Pg7j7ee5c21ly9wve5HB+wTP79JZBA+jkzXbxnQBrdgqm4Nen4dHu4+DKSDmGZKX56V8X1IIpfW2fqqW0upuaUgGA9dmhduxrayUtPhl4QH/dCqkc/GttNDbmBSiXRixOKzo+5co+4m4pUD6mkQd41eJ//zuMKSRR0LGEBiUQxV1uVD76h3MepJkLXoWVPPk21i70x6120Vkmp8dWOey2VQWtpwb41zqd3PJlLQg/7R2mK88q+/9w6P87PxRVvUpnGDRPZ3IvTDawLpTXbmhv3wvuJhU33TsDdl5paU0zAG0B3AsQpowuTePjuIqkqPtP4PrtSK7OdCfkYNrt+pHQEhUxgIDoNmP89UfMud9TAC7K+Dq/QMeGW6+JlOKzPUyzmoCk5x8pqVA==
  template:
    metadata:
      creationTimestamp: null
      name: musicbot
      namespace: argocd
