---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: musicbot
  namespace: argocd
spec:
  encryptedData:
    owner: AgC/WtsMtgummorHCm8u95BN5ZizlDUg+K+D3TnLgBnNud6w5ADD0HBHHbEI1e0gjwSMkldn//gLTpBwzCs69Zk+a4tQ+I1nCTfofU8rMtMhFK/UgzbYlcA0oZs78cSlJQUNtw3YrHlRrb/6DjxAxBG35C3SFtZdiGJBDGI/4o83m9I7iPlOhl+4oFgE1bTnGaou6pQQXjaX9/7g9xVBjSOMu8YGFZLNEmlNRuDMErBAcW4TrHMEMLOmNCyZHLqcfobJtTxAev3UC8v22vQqf/alWVrMOR2bdyRm/S5QYKw93HFPodKkR9OL0q6CPtHbQaPkamIErfK7X/GRBSDMCKB2KhaRlFuuhgGb8ZLw8joHMkcn++Z0TjXTDQuCc/Qwe8WFTzu9AIOZ9lHEMfWBkZMX38cajMKCxcJzGGnvWghqUmeoeiUsuE1a9YsK4e8bEOIVcJEpoRHe496d1eambVp+PusqLAm94ibuL2cwhLRXAHillwlwX8bJv/FpGk/H2bvugZFkV6DXKtUcwWJoAEMCtN27OgQVeknJj2CzkAISKnG89GsaLp7FllZiR1jwwfUyv0VB96vlHO/GTSAClATEaZ1bGIeFxnXjeE0L4Q+evRKAFplAEaAcPhaicxEaxfmt+JafTI4MyCXR+ZtsNpFgYqNzU7YSPIOuZbwr5qeTcgg28/GrkLEW4g/Vy5j2CfxZRbE70DLAO17hPQrNK75leKA=
    token: AgA8EWRVsTyY4k5QAc6gI23RzjsCWys4H5RNx/jZu8aSH7tUWX9iZvwlSIdRDTGvhjYQ8CuhvWtOZtxK21RygomZJv6piPgSY0g8E6W8PmMdVVOEJs/V4VjRGTWzHWlgGRpnGOvPgBCLrFBvAn4EhojMNCUgixVeXluKaD03qIHnuP3eXaErCSx4P63iaQszecxOSzwA7a4qWcSwR4M1ngnhVq+Oi73z33bZE/KKrkP186TN/lQoSdLA4BpPzDAJ4Z2/9V4y3axSfgNBdvj29fZGQ5xZGO0M8fctnSKf0LeDHSKB92eQ0VVo9/EGJ1VhNP3mI/JLTUIBhyK4mn/IRNUhAKKtdBNuJcC3X4jO87hCJ55HeYjsYQmSpj5YoKAbBLiGedO7RqTa1YEK0bp8LsrUXwY56W2n6/ZuNlaOOwIPgkTfIZ+RH3WSdb8MoeDvMtGQRIPs6IDImSp9uQW6pz1etK18MmU04x3pj1z2jTpVCkr1WcPkAzLIA/uHJnSrAkOioS2I06K6m0p8oEPgpwidMbX5QAP99JeX5TFks6H8EjyjA5abZLIZpIWivL1Q8NrtblhcT9GGJZUHwCVjV9SB5zjhYJQfZM9Q4qAVf1nQQpVLSXnuwygMoMw5+5m0jO2Hyhx5mDJuZ0Iw7Ug3hCkwaK6Smv9SfQSN4P2zPHR888L+0yicIlb0dF4r8tbrWI7CE70F/PB87seW7Jiom9/sCuiuBgk7eVS/W6Jcc5UPNqh+moVA0W5dDRJFaHw1AFFVsn8O2StXb1gUEw==
  template:
    metadata:
      creationTimestamp: null
      name: musicbot
      namespace: argocd
