name: Lint and Dry-Run Manifests

on:
  pull_request:
    branches:
      - main
    # yamlファイルやチャートに変更があったときだけ実行
    paths:
      - 'argocd/**'
      - '.github/workflows/test-manifests.yaml'

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.18.6'

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.34.0'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs argocd/applications,argocd/apps

      - name: Validate and Dry-Run
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Testing manifests with targetRevision: ${BRANCH_NAME}"
          
          helm template argocd/apps/ --set config.targetRevision=${BRANCH_NAME} | kubectl apply --dry-run=client -f -