
name: Publish chart

on:
  push:
    branches:
      - main
      - feature/argocd-bootstrap # for test

jobs:
  release:
    permissions:
      contents: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Install dependent repositories
        run: |
          helm repo add argo-cd https://argoproj.github.io/argo-helm
          helm repo update

      - name: Package and Release Helm Chart
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          CHART_DIR="." 
          
          BASE_VERSION=$(helm show chart $CHART_DIR | grep '^version:' | awk '{print $2}')
          NEW_VERSION="${BASE_VERSION}-${SHORT_SHA}"
          
          echo "Packaging chart with version: ${NEW_VERSION}"
          helm package $CHART_DIR --version "$NEW_VERSION"
          
          TAG_NAME="chart-${NEW_VERSION}"
          
          if gh release view "$TAG_NAME" >/dev/null 2>&1; then
            echo "Release $TAG_NAME already exists. Uploading asset..."
            gh release upload "$TAG_NAME" *.tgz --clobber
          else
            echo "Creating new release $TAG_NAME..."
            gh release create "$TAG_NAME" *.tgz --title "Chart Release ${NEW_VERSION}" --notes "Automated release for commit ${SHORT_SHA}"
          fi
